### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by t-m-lee** [williamkapke/node-eachline#5]
I haven't looked into this yet but basically I downloaded a large file from S3 which contains a JSON object per line. I was trying to create a stream out of the file content buffer that I get from S3 then run it through eachline to process each JSON object.

```javascript
    s3.getObject(params, function(err, data) {
      if (err) {
        // log
        return;
      }

      var lines = [];

      var bufferStream = new stream.PassThrough();
      bufferStream.end(data.Body);
      
      console.log("BEFORE");
      eachline(bufferStream, function(line){
        lines.push(line);
      }).on('finish', function() {
        console.log(lines);
        console.log("DONE");
      });
    });
```

"BEFORE" gets logged and then boom

```
RangeError: Maximum call stack size exceeded
    at new Uint8Array (native)
    at Buffer.subarray (native)
    at Buffer.slice (buffer.js:611:23)
    at next (/.../node_modules/eachline/eachline.js:119:18)
    at signaled (/.../node_modules/eachline/eachline.js:151:11)
    at Transformer._pushline (/.../node_modules/eachline/eachline.js:161:2)
    at next (/.../node_modules/eachline/eachline.js:126:10)
    at signaled (/.../node_modules/eachline/eachline.js:151:11)
    at Transformer._pushline (/.../node_modules/eachline/eachline.js:161:2)
    at next (/.../node_modules/eachline/eachline.js:126:10)
```

**Comment by williamkapke** [comment]
Ouch. yeah, that's a big file.

The problem is most likely the recursion of the `next()` function.

If https://github.com/williamkapke/node-eachline/blob/master/eachline.js#L126 was wrapped in a `setImmediate` it would probably be OK.

**Comment by t-m-lee** [comment]
Yeah, seems like that would do the trick. Want a PR?

**Comment by williamkapke** [comment]
Give it a try, if it works... heck yeah- send a PR!
